version: '3'

services:
  publications:
    image: ghostsnetwork/publications:latest
    ports:
      - "5300:80"
    depends_on:
      - db
    environment:
      - MONGO_ADDRESS=db:27017
      - ASPNETCORE_ENVIRONMENT=Development

  reactions:
    image: ghostsnetwork/reactions:latest
    ports:
      - "5200:80"
    depends_on:
      - db
    environment:
      - MONGO_ADDRESS=db:27017
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"

  gateway:
    image: ghostsnetwork/gateway:latest
    ports:
      - "5000:80"
    depends_on:
      - publications
      - reactions
    environment:
      - PUBLICATIONS_ADDRESS=http://publications
      - REACTIONS_ADDRESS=http://reactions
      - ASPNETCORE_ENVIRONMENT=Development

  spa:
    build: .
    ports:
      - "4200:80"
    depends_on:
      - gateway
