version: '3'

services:
  publications:
    image: ghcr.io/ghosts-network/publications:latest
    ports:
      - "5300:80"
    depends_on:
      - db
    environment:
      - MONGO_ADDRESS=db:27017
      - ASPNETCORE_ENVIRONMENT=Development

  reactions:
    image: ghcr.io/ghosts-network/reactions:latest
    ports:
      - "5200:80"
    depends_on:
      - db
    environment:
      - MONGO_ADDRESS=db:27017
      - ASPNETCORE_ENVIRONMENT=Development

  profiles:
    image: ghcr.io/ghosts-network/profiles:latest
    ports:
      - "5400:80"
    depends_on:
      - db
    environment:
      - MONGO_ADDRESS=db:27017
      - ASPNETCORE_ENVIRONMENT=Development

  account:
    image: ghcr.io/ghosts-network/account:latest
    ports:
      - "6030:80"
    depends_on:
      - profiles
    environment:
      - ASPNETCORE_ENVIRONMENT=Development

  db:
    image: mvertes/alpine-mongo
    ports:
      - "27017:27017"

  gateway:
    image: ghcr.io/ghosts-network/gateway:latest
    ports:
      - "5000:80"
    depends_on:
      - publications
      - reactions
      - profiles
      - account
    environment:
      - PUBLICATIONS_ADDRESS=http://publications
      - REACTIONS_ADDRESS=http://reactions
      - PROFILES_ADDRESS=http://profiles
      - ASPNETCORE_ENVIRONMENT=Development

  spa:
    build: .
    ports:
      - "4200:80"
    depends_on:
      - gateway
